apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-${ZONE}-${COMPONENT}
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}-${ZONE}-${COMPONENT}
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
        deployment: ${NAME}-${ZONE}-${COMPONENT}
      type: ClusterIP
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ${NAME}-${ZONE}-${COMPONENT}
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
    spec:
      host: ${NAME}-${ZONE}-${COMPONENT}-${Host}
      to:
        kind: Service
        name: ${NAME}-${ZONE}-${COMPONENT}
        weight: 100
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${NAME}-${ZONE}-${COMPONENT}
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
        role: frontend
    spec:
      strategy:
        type: RollingUpdate
      replicas: 1
      revisionHistoryLimit: 5
      selector:
        matchLabels:
          app: ${NAME}-${ZONE}
          component: ${COMPONENT}
          deployment: ${NAME}-${ZONE}-${COMPONENT}
      template:
        metadata:
          labels:
            app: ${NAME}-${ZONE}
            component: ${COMPONENT}
            deployment: ${NAME}-${ZONE}-${COMPONENT}
            role: frontend
        spec:
          containers:
            - name: ${NAME}-${ZONE}-${COMPONENT}
              image: ghcr.io/bcgov/nr-nrpti/public-nrpti:${ZONE}
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: RealIpFrom
                  value: 10.97.0.0/16
                - name: AdditionalRealIpFromRules
                - name: IpFilterRules
                  value: "#allow all; deny all;"
                - name: CONFIG_ENDPOINT_HOST
                  value: NRPTI_API_SERVICE_HOST
                - name: CONFIG_ENDPOINT_PORT
                  value: NRPTI_API_SERVICE_PORT
              resources:
                limits:
                  cpu: 250m
                  memory: 250Mi
                requests:
                  cpu: 10m
                  memory: 50Mi
              livenessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
parameters:
  - name: NAME
    description: The name assigned to all of the frontend objects defined in this template.
    displayName: Name
    required: true
    value: nrpti
  - name: ZONE
    description: Deployment zone (dev, test, prod or PR number)
    displayName: Deployment Zone
    required: true
  - name: COMPONENT
    description: Component name
    displayName: Component
    required: true
    value: nrced
  - description: A name used for all objects in the build or deploy group
    displayName: Group name
    name: GROUP_NAME
    required: true
    value: nrpti
  - name: RUNTIME_IMAGE_NAMESPACE
    required: true
    value: f00029-tools
  - name: RUNTIME_IMAGE_NAME
    required: true
    value: public-nrced
  - name: RUNTIME_IMAGE_TAG
    required: true
    value: latest
  - name: Host
    value: f00029-dev.apps.silver.devops.gov.bc.ca
