name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  builds:
    name: Builds
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [api, public-nrpti]
        include:
          - package: api
            directory: backend
            dockerfile: Dockerfile
          # - package: admin-nrpti
          #   directory: frontend
          #   dockerfile: Dockerfile
          - package: public-nrpti
            directory: frontend
            dockerfile: Dockerfile-public-nrpti
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@ace71f7a527ca6fc43c15c7806314be5a4579d2c # v2.3.0
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          build_context: ${{ matrix.directory }}
          build_file: ${{ matrix.directory }}/${{ matrix.dockerfile }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          # triggers: ('${{ matrix.directory }}/')

  init:
    name: Init
    needs: [builds]
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy Init
        uses: bcgov/action-deployer-openshift@v4.0.0
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          file: ./common/openshift.database.yml
          overwrite: true
          parameters: |
            -p MONGODB_ADMIN_PASSWORD=${{ secrets.MONGODB_ADMIN_PASSWORD }}
            -p MONGODB_DATABASE_NAME=${{ secrets.MONGODB_DATABASE_NAME }}
            -p MONGODB_USER=${{ secrets.MONGODB_USER }}
            -p MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}

  deploy:
    name: Deploy
    needs: [builds]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [api, public-nrpti
        include:
          - package: api
            file: ./tools/api/api.dc.yaml
          # - component: admin-nrpti
          #   file: ./tools/angular-on-nginx/admin-nrced.dc.yaml
          - package: public-nrpti
            file: ./tools/angular-on-nginx/public-nrced.dc.yaml
    steps:
      - name: Deploy ${{ matrix.package }}
        uses: bcgov/action-deployer-openshift@v4.0.0
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          file: ${{ matrix.file }}
          overwrite: true

  # # https://github.com/bcgov/action-deploy-ghcr
  # deploys:
  #   name: Deploys (${{ github.event.number }})
  #   needs: [builds]
  #   secrets: inherit
  #   uses: ./.github/workflows/deploy.yml
  #   with:
  #     triggers: ('api/' 'angular/')
